# Connection pool settings
datasource.url=jdbc:postgresql://localhost:5432/gym-db
datasource.username=postgres
datasource.password=postgres
datasource.driver-class-name=org.postgresql.Driver
datasource.connection-pool.maximum-size=10

# Persistence settings
persistence.unit-name=gym-persistence-unit
persistence.show-sql=true
persistence.generate-ddl=false
persistence.database-platform=postgresql