# Application properties
spring.application.name=GymCRM
spring.profiles.active=dev

# Server settings
server.port=8080
server.servlet.context-path=/GymCRM

# Connection pool settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/gym-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=public
spring.datasource.hikari.maximum-pool-size=10

# Persistence settings
spring.jpa.properties.hibernate.ejb.persistenceUnitName=gym-persistence-unit
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.dev.sql
spring.sql.init.data-locations=classpath:data.dev.sql
spring.jpa.hibernate.ddl-auto=none

# JWT settings
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurpose123456
jwt.access.expiration-seconds=3600
jwt.refresh.expiration-seconds=1296000

# Actuator settings
management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.endpoint.health.show-details=always