# Connection pool settings
spring.jpa.database=POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/gym-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=public
spring.datasource.hikari.maximum-pool-size=10

# Persistence settings
spring.jpa.properties.hibernate.ejb.persistenceUnitName=gym-persistence-unit
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.dev.sql
spring.sql.init.data-locations=classpath:data.dev.sql
spring.jpa.hibernate.ddl-auto=none

# JWT settings
app.security.jwt.enabled=true
app.security.jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurpose123456
app.security.jwt.access.expiration-seconds=3600
app.security.jwt.refresh.expiration-seconds=1296000

# OpenAPI settings
springdoc.show-actuator=false