spring:
################### Application properties ####################
  application:
    name: statistics-app
  profiles:
    active: dev

  ################# RabbitMQ Messaging settings ###################
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    queue:
      name: gym.trainings.queue
    exchange:
      name: gym.exchange
    routing-key: gym.trainings.queue
    dlqueue:
      name: gym.trainings.dlqueue
    dlexchange:
      name: gym.dlexchange
    dlrouting-key: gym.trainings.dlqueue

####################### Server settings #######################
server:
  port: 8082

############ Eureka Discovery Client settings ################
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
