spring:
##################### MongoDB settings ##########################
  data:
    mongodb:
      host: mongo
      port: 27017
      database: gym_db
      username: admin
      password: admin
      authentication-database: admin

  ################# RabbitMQ Messaging settings ###################
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    queue:
      name: gym.trainings.queue
    exchange:
      name: gym.exchange
    routing-key: gym.trainings.queue
    dlqueue:
      name: gym.trainings.dlqueue
    dlexchange:
      name: gym.dlexchange
    dlrouting-key: gym.trainings.dlqueue

####################### Server settings #######################
server:
  port: 8082

############ Eureka Discovery Client settings ################
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry-server:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: statistics-app


