spring:
##################### Datasource settings #######################
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres_db:5432/gym-db
    username: admin
    password: admin
    hikari:
      schema: public
      maximum-pool-size: 10

##################### Persistence settings #######################
  jpa:
    database: postgresql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: none
        ejb:
          persistenceUnitName: gym-persistence-unit

################# RabbitMQ Messaging settings ###################
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    queue:
      name: gym.trainings.queue
    exchange:
      name: gym.exchange
    routing-key: gym.trainings.queue
    dlqueue:
      name: gym.trainings.dlqueue
    dlexchange:
      name: gym.dlexchange
    dlrouting-key: gym.trainings.dlqueue


#################### Logger settings ########################
logging:
  level:
    io.github.resilience4j: INFO
    org.springframework.cloud.loadbalancer: INFO
    com.epam.laboratory.app.service.TrainingStatisticsServiceImpl: INFO

######################### JWT settings ##########################
app:
  security:
    jwt:
      enabled: true
      encryption-algorithm: HS256
      secret: mySecretKeyForJWTTokenGenerationAndValidationPurpose123456
      access-ttl-seconds: 3600       # 1 hour
      refresh-ttl-seconds: 1296000   # 15 days
      issuer: gym-api
      audience: gym-app

###################### OpenAPI settings #########################
springdoc:
  show-actuator: false

############ Eureka Discovery Client settings ################
eureka:
  client:
    service-url:
      defaultZone: http://registry-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: main-app